"""empty message

Revision ID: 23350845590f
Revises: 4ca332f44030
Create Date: 2022-08-06 08:58:31.058712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23350845590f'
down_revision = '4ca332f44030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('artist', 'web_link')
    op.drop_column('artist', 'looking_venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('looking_venues', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('web_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
