"""empty message

Revision ID: 372f371f77ea
Revises: 23350845590f
Create Date: 2022-08-06 09:10:11.343472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372f371f77ea'
down_revision = '23350845590f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.drop_column('venue', 'web_link')
    op.drop_column('venue', 'looking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('looking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('venue', sa.Column('web_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
